CLICK_SEARCH_BOX_ID = "searchData"
SEARCH_BUTTON_CLASS_NAME = "searchBtn"
FIRST_ITEM_CLASS_NAME = "plink"
ADD_BASKET_BUTTON_CLASS_NAME = "addBasketUnify"
EXPECTED_ITEM = "https://www.n11.com/urun/apple-iphone-15-pro-max-256-gb-apple-turkiye-garantili-43821338?magaza=troyapple"
ITEM_CLASS_NAME = "prodDescription"
BASKET_TOTAL = "/html/body/div[1]/header/div/div/div/div[2]/div[4]/a"
SEARCH_DATA = "iphone 15 telefon"