expected_url_campaignFilter ="https://www.n11.com/arama?q=Macbook+air&hscp=hediyeli-kampanya_anlik-indirim&hdfl=cats_camps_m_ppf"
CONTROL_SEARCH_BOX_XPATH = "//a[@href='https://www.n11.com/arama?q=macbook+air']"
EXPECTED_URL_SEARCH_BOX = "https://www.n11.com/arama?q=macbook+air"

CLICK_SEARCH_BOX_ID = "searchData"
SEARCH_BUTTON_CLASS_NAME = "searchBtn"
CLICK_LOCATION_BTN_XPATH ="/html//div[@id='headerSetMyLocationBtn']"
LOCATION_NAME_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[2]/div[1]/p"
FIND_CATEGORY_NAME_H = "/html/body/div[1]/header/nav/ul/li[2]/a"
SUBCATEGORY_XPATH = "/html/body/div[1]/header/nav/ul/li[2]/div/ul/li[2]/a"
SELECT_DISTRICT_CSS ="select#headerMyLocationDistrictId"
SELECT_CITY_CSS ="select#headerMyLocationCityId"
LOCATION_BUTTON_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[2]/div[1]/div/div[1]/label/span"
SELECTED_BRAND_ITEM_XPATH ="//*[@id='contentListing']/div/div[2]/div[2]/section/div[1]/div[3]/div/ul/div/div/li[2]/a"
SELECTED_BRAND_NAME_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[1]/section[9]"
SELECTED_MODEL_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[1]/section[9]/div/div[2]/div[1]/label/span"
CONTROL_FILTER_MESSAGE_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[1]/section[2]/div/div[1]"
DELETE_BUTTON_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[1]/section[2]/span"
FILTER_RESULT_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[1]/div"
DELETE_FILTER_RESULT_XPATH ="/html/body/div[1]/div[4]/div/div[1]/ul/li[3]/a"
CLICK_SORTING_DROPDOWN_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[1]"
CLICK_SORTING_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[1]/span"
CLICK_LOW_SORTING_BOX = "/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[2]"
CLICK_SALES_QUANTITY_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[4]"
CLICK_HIGH_SORTING_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[3]"
CLICK_REVIEWS_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[5]"
CLICK_NEWEST_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[6]"
CLICK_REVIEW_RATE_BOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[7]"
CLICK_SELLER_GRADE_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[8]"
CLICK_MANUALLY_REMOVING_FILTERS_XPATH = "//div[@id='contentListing']//div[@class='filterArea']/section[2]/div/div[1]/div[@class='choice']/span[@class='close']"
CLICK_X_BUTTON_TWO ="/html//div[@id='contentListing']//div[@class='filterArea']/section[2]//div[@class='choice']/span[@class='close']"
CLICK_INSTANT_DISCOUNT_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[1]/section[3]/div/div/div[2]/label/span"
CLICK_GIFT_CAMPAIGNS_CHECHBOX_XPATH ="/html/body/div[1]/div[4]/div/div[2]/div[1]/section[3]/div/div/div[1]/label/span"
CLICK_CAMPAIGN_FILTER_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[1]/section[3]"
CLICK_SAME_DAY_DELIVERY_XPATH = "//label[@for='local-search-checkbox']/span"
CLICK_LOCATION_SPECIFIC_DELIVERY_XPATH = "//label[@for='local-special-checkbox']/span"
CONTROL_SWITCH_BUTTON_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[1]/div[2]/div[1]/div/div[1]/label/input"
TOP_MY_LOCATION_XPATH = "/html/body/div[1]/header/div/div/div/div[2]/div[1]/div[2]/div[2]/div/div[2]/div"
MY_LOCATION_BTN_DISTRICT_XPATH = "/html/body/div[1]/header/div/div/div/div[2]/div[1]/div[2]/div[2]/div/div[1]/div[2]/div[1]/select"
MY_LOCATION_BTN_CITY_XPATH="/html/body/div[1]/header/div/div/div/div[2]/div[1]/div[2]/div[2]/div/div[1]/div[1]/div[1]/select"
MY_LOCATION_BTN_XPATH = "/html/body/div[1]/header/div/div/div/div[2]/div[1]/div[1]"



LOCATION_NAME_TEXT = "Bölgene Özel Avantajları Kaçırma!:"
LOCATION_NAME__ASSERT_TEXT="Location mismatch"
ASSERT_MESSAGE_PRICE_LOW ="Sırala: Artan fiyat"
CLICK_SORTING_DROPDOWN_EXPECTED="NUMARA11"
DELETE_FILTER_RESULT_EXPECTED ="Bilgisayar"
FILTER_RESULT_EXPECTED = "Bilgisayar için 460 sonuç bulundu."
FILTER_RESULT_EXPECTED_ASSERT ="Filtering process failed"
ASSERT_MESSAGE_SORTING_TEXT = "The sorting preference is incorrect."
DELETE_FILTER_RESULT_EXPECTED_ASSERT = "The clear filters button is non-functional"
CONTROL_EXPECTED_FILTER_ASSERT ="Does not match the selected filter!"
CONTROL_EXPECTED_FILTER = "Intel i5-1135G7"
PRICE_HIGH_ASSERT ="Sırala: Azalan fiyat"
SALES_QUANTITY_ASSERT = "Sırala: Satış miktarı"
REVIEWS_ASSERT = "Sırala: Yorum sayısı"
NEW_ITEMS_ASSERT ="Sırala: Yeni ürün"
REVIEW_RATE_ASSERT = "Sırala: Ürün Notu"
CONTROL_LOCATION_PANEL_ASSERT = "Inactive checkbox"