CLICK_SEARCH_BOX_ID = "searchData"
SEARCH_BUTTON_CLASS_NAME = "searchBtn"

SECOND_PRODUCT_TITLE = "/html/body/div[1]/div[4]/div/div[2]/div[2]/div[1]/div/div[2]/div[1]/div[1]/div/h1"
ITEM_NAME= "apple-macbook-air-mgn63tua-apple-m1-8-gb-256-gb-ssd-133-macos-dizustu-bilgisayar-gri-1715113"
CLICK_FIRST_ITEM_XPATH = "/html/body/div[1]/div[4]/div/div[2]/div[2]/section/div[2]/ul/li[1]/div/div/a"
ITEM_TARGET_CLASS_NAME ="plink"
MORE_PRODUCT_FEATURES = "/html/body/div[1]/div[4]/div/div[4]/div/div[1]/div[3]/div/p"
REVIEW_PRODUCT_ID="readReviews"
STARS_FOUR_XPATH = "/html/body/div[1]/div[4]/div/div[4]/div/div[2]/div[2]/div/div/div/div[2]/div[1]/div[2]/div[2]/span[1]"
STARS_FIVE_XPATH = "/html/body/div[1]/div[4]/div/div[4]/div/div[2]/div[2]/div/div/div/div[2]/div[1]/div[2]/div[1]"
RATING_STAR_TARGET = "/html/body/div[1]/div[4]/div/div[4]/div/div[2]/div[1]/div/div[1]"
STAR_ASSERT = "5"
ASSERT_STAR_TEXT ="Rating  is false"
CARGO_DETAILS_BUTTON_CLASS_NAME = "detailPreviewBtn"
CARGO_DETAILS_BUTTON_ASSERT ="Tüm Detayları Gör"
CARGO_DETAILS_BUTTON_TEXT="Button name is incorrect"
CARGO_DETAILS_WINDOW_CLOSE_XPATH ="/html/body/div[15]/div/div/div[2]/span"